- block:

  - name: Install Certbot
    yum:
      name: [certbot,certbot-apache,certbot-nginx]
    ignore_errors: yes
    
  - pip:
      name: [requests==2.6.0,urllib3]
      extra_args: --upgrade --force-reinstall --ignore-installed
      
  - name: Set up automatic renewal
    shell: echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto renew" | sudo tee -a /etc/crontab > /dev/null
  
  when: preend_certbot



