- name: Install maven
  apt:
    name: maven



- name: Add RocketMQ User
  user:
    name: rocketmq
    shell: /usr/sbin/nologin
    home: /opt/rocketmq
    create_home: no

- name: Download RocketMQ
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /opt/
    remote_src: yes
    owner: rocketmq
    group: rocketmq

- name:   change dirctory
  shell:
     cd /opt/rocketmq-all-4.7.0-source-release

- name: build the binary artifact
  shell:
    mvn -Prelease-all -DskipTests clean install -U
 
    
    
- shell: mv /opt/rocketmq-* /opt/rocketmq

- name: Setting Environment
  shell: echo 'export PATH="$PATH:/opt/rocketmq/bin"' >> /etc/profile

- name: Configuration Name Server
  copy: 
    src: runserver.sh
    dest: /opt/rocketmq/bin/
    owner: rocketmq
    group: rocketmq

- name: Configuration Broker
  copy: 
    src: runbroker.sh
    dest: /opt/rocketmq/bin/
    owner: rocketmq
    group: rocketmq
    
- name: Configuration RocketMQ Name Server
  copy:
    src: mqnamesrv.service
    dest: /lib/systemd/system/

- name: Configuration RocketMQ Broker Server
  copy:
    src: mqbroker.service
    dest: /lib/systemd/system/

- name: Start RocketMQ Name Server
  service:
    name: mqnamesrv
    state: started
    enabled: yes

- name: Start RocketMQ Broker Server
  service:
    name: mqbroker
    state: started
    enabled: yes

- name: Setting File Permission
  shell: |
    find /opt -type f -exec chmod 640 {} \;
    find /opt -type d -exec chmod 750 {} \;  

- name: Setting Owner and  Group
  shell: chown -R rocketmq. /opt/rocketmq


