#Installnation on  different os is same  
- name: Download RocketMQ
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /opt/
    remote_src: yes
    owner: rocketmq
    group: rocketmq 
    
- name: rename 
  shell: mv /opt/rocketmq-* /opt/rocketmq

- name: Setting Environment
  shell: echo 'export PATH="$PATH:/opt/rocketmq/bin"' >> /etc/profile

- name: Configuration RocketMQ Name Server
  copy:
    src: mqnamesrv.service
    dest: /lib/systemd/system/

- name: Configuration RocketMQ Broker Server
  copy:
    src: mqbroker.service
    dest: /lib/systemd/system/

- name: Start RocketMQ Name Server
  service:
    name: mqnamesrv
    state: started
    enabled: yes

- name: Start RocketMQ Broker Server
  service:
    name: mqbroker
    state: started
    enabled: yes




