#Installnation on  different os is same  
- name: Download RocketMQ
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /opt/
    remote_src: yes
   
    
- name: rename 
  shell: mv /opt/rocketmq-* /opt/rocketmq

- name: Setting Environment
  shell: echo 'export PATH="$PATH:/opt/rocketmq/bin"' >> /etc/profile

- name: Configuration RocketMQ Name Server
  copy:
    src: mqnamesrv.service
    dest: /lib/systemd/system/

- name: Configuration RocketMQ Broker Server
  copy:
    src: mqbroker.service
    dest: /lib/systemd/system/

- name: Start RocketMQ Name Server
  service:
    name: mqnamesrv
    state: started
    enabled: yes

- name: Start RocketMQ Broker Server
  service:
    name: mqbroker
    state: started
    enabled: yes

# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/rocketmq  /data/wwwroot
    ln -sf /opt/rocketmq/conf /data/config


