#Installnation on  different os is same  
- name: Download RocketMQ
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /data/wwwroot
    remote_src: yes
       
- name: Rename for rocketmq 
  shell: |
    mv /data/wwwroot/rocketmq-* /data/wwwroot/rocketmq 

- name: Setting Environment
  shell: export PATH="$PATH:/data/wwwroot/rocketmq/bin"

- name: Configuration RocketMQ Name Server
  copy:
    src: mqnamesrv.service
    dest: '/lib/systemd/system/mqnamesrv.service'

- name: Configuration RocketMQ Broker Server
  copy:
    src: mqbroker.service
    dest: '/lib/systemd/system/mqbroker.service'

- name: Start and Enable  RocketMQ Name Server
  service:
    name: mqnamesrv
    state: started 
    enabled: yes

- name: Start and Enable  RocketMQ Broker Server
  service:
    name: mqbroker
    state: started
    enabled: yes
   
# set soft link, -f enforce the exist links
# ln -sf src des
#- name: set soft link
#  shell: |
#    ln -sf /opt/rocketmq  /data/wwwroot
#    ln -sf /opt/rocketmq/conf /data/config

# Check version,
# must use sudo sh -c to solve the no-root permission
#- block:
#  - name: Check rocketchat Version
#    shell: sudo sh -c "echo `` >> /data/logs/install_version.txt"


check service state
- name: Check mqnamesrv Service
  shell: systemctl status mqnamesrv | grep Active*
  register: check_mqnamesrv_service
  notify: check_mqnamesrv_service

- name: Check mqbroker Service
  shell: systemctl status mqbroker | grep Active*
  register: check_mqbroker_service
  notify: check_mqbroker_service


