name: Docs Build and Upload

on: 
  push:
    paths: docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - name: npm install vuepress
      run: |
       sudo npm install -g vuepress
        
    - name: vuepress build
      run: |
        cd docs
        sudo vuepress build .
        git clone https://github.com/Websoft9/websoft9.github.io.git
        cp -r html/*  websoft9.github.io/docs/
        sudo chown -R runner: websoft9.github.io
        cd  websoft9.github.io
        git config --local user.email "xu_junkai@foxmail.com"
        git config --local user.name "Mozlk"
        git add .
        git commit -m "Update Docs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        directory: docs/websoft9.github.io
        repository: Websoft9/websoft9.github.io
